# Generated by Django 3.0.8 on 2020-08-16 19:12

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('enable_alert', models.BooleanField(default=False)),
                ('alert_text', wagtail.core.fields.RichTextField(blank=True)),
                ('alert_colour', models.CharField(choices=[('R', 'Red'), ('G', 'Green')], default='R', max_length=1)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_col_heading', models.CharField(blank=True, max_length=200)),
                ('footer_col', wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('telephone', wagtail.core.blocks.StructBlock([('telephone', wagtail.core.blocks.CharBlock(classname='telephone'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('email', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock(classname='email'))]))], blank=True)),
            ],
            options={
                'verbose_name': 'First Footer Column',
            },
        ),
        migrations.CreateModel(
            name='FooterColumnTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_col_two_heading', models.CharField(blank=True, max_length=200)),
                ('footer_col_two', wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('telephone', wagtail.core.blocks.StructBlock([('telephone', wagtail.core.blocks.CharBlock(classname='telephone'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('email', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock(classname='email'))]))], blank=True)),
            ],
            options={
                'verbose_name': 'Second Footer Column',
            },
        ),
    ]
