# Generated by Django 3.0.8 on 2020-08-25 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0002_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 9, 50, 33, 253195)),
        ),
    ]
