# Generated by Django 3.0.8 on 2020-08-25 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0003_alert_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 10, 30, 8, 62184)),
        ),
    ]
