# Generated by Django 3.0.8 on 2020-08-27 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0007_auto_20200826_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 14, 59, 28, 722282)),
        ),
    ]
