# Generated by Django 3.0.8 on 2020-08-27 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0008_auto_20200827_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 15, 4, 17, 188498)),
        ),
    ]
